apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openvoting
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ required "host is required" .Values.host }}
    secretName: openvoting-tls
  rules:
  - host: {{ required "host is required" .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openvoting
            port:
              number: 80
