apiVersion: v1
kind: Secret
metadata:
  name: openvoting-secrets
  labels:
    app: openvoting
type: Opaque
stringData:
  db-connection-string: {{ .Values.env.connectionStrings.database | quote }}
  discord-client-secret: {{ .Values.env.discord.clientSecret | quote }}
  discord-bot-token: {{ .Values.env.discord.botToken | quote }}
  jwt-signing-key: {{ .Values.env.jwt.signingKey | quote }}
  storage-connection-string: {{ .Values.env.blobStorage.connectionString | quote }}