image:
  repository: ghcr.io/amyjeanes/openvoting/openvoting
  tag: latest
imagePullSecrets: []

resources:
  requests:
    memory: 256Mi
    cpu: 10m
  limits:
    memory: 256Mi

host: ""

env:
  connectionStrings:
    database: ""
  discord:
    clientId: ""
    clientSecret: ""
    botToken: ""
    guildId: ""
    adminRoleIds: ""
  jwt:
    signingKey: ""
  blobStorage:
    connectionString: ""
    containerName: ""
    publicBaseUrl: ""
